name: Node CI

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Use Node 12.x
          uses: actions/setup-node@v3
          with:
            node-version: '12.x'
      - name: npm install and build
        run: |
          npm ci
          npm run build:ci
      - name: Archive artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist-without-markdown
          path: |
            dist
            !dist/**/*.md